import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { SqliteWorldStore } from '@aegis/db';
import { openNodeDatabase } from '@aegis/db/node';
import {
  GENERATION,
  MISSION_TEMPLATES,
  greatCircleDistance,
  objectivesMet,
  simInstant,
  type Mission,
} from '@aegis/domain';
import { importReferenceData } from '@aegis/ingest';
import {
  SimulationRunner,
  replayComparable,
  replayWorld,
  type Checkpoint,
  type LogEntry,
  type SimCommand,
} from '@aegis/sim';
import { ManualHostClock } from '@aegis/sim/testing';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { buildCatalogue, starterOrders, type AerodromeRow } from '../fleet/catalogue';
import { insertWaypoint, moveWaypoint, refuelForRoute, type PlanDraft } from '../fleet/plan-edit';
import { missionFeatures } from '../map/mission-features';
import {
  bindReferenceDb,
  loadAerodrome,
  loadAircraftTypes,
  loadLargeAerodromes,
} from '../reference/queries';
import { bindSimDb, loadMissionLog, loadRecentLog } from '../sim/log-queries';
import { FLIGHT_REFERENCE_INPUTS } from '../testing/flight-fixtures';
import {
  blankForm,
  configurationFromForm,
  configurationOf,
  evaluationOf,
  formFromMission,
  groupOf,
  listMissions,
  missionProgress,
  readiness,
  suggestedTarget,
} from './mission-logic';
import { chooseOperatingArea } from './operating-area';

/*
 * The mission layer end to end, through the code the application runs: reference data imported
 * by the pipeline, a starter fleet, a mission created from the form, its route edited with the
 * flight planner's own functions, accepted, launched, flown and completed; the log read back from
 * SQLite; the application closed and reopened; and an opportunity generated by the world taken up
 * and flown through the same framework. Only the window and the map renderer are absent.
 */

const EPOCH = simInstant(Date.UTC(2026, 9, 4, 12, 0, 0));
const newWorld = () => ({ seed: 'mission-scenario', epoch: EPOCH });
const AIRCRAFT = 'AEGIS-TR-001';
const TRAINING = 'MSN-000001';

describe('missions: end-to-end scenario', () => {
  let directory: string;
  let path: string;

  async function openSession() {
    const database = openNodeDatabase(path);
    bindReferenceDb(database.db);
    bindSimDb(database.db);
    const host = new ManualHostClock();
    const runner = await SimulationRunner.open({
      store: new SqliteWorldStore(database.db),
      host,
      newWorld,
    });
    const execute = (command: SimCommand) => {
      runner.execute(command);
    };
    const run = (realMs: number) => {
      for (let elapsed = 0; elapsed < realMs; elapsed += 100) {
        host.elapse(100);
        runner.advance();
      }
    };
    const view = () => runner.view();
    const aircraft = (id = AIRCRAFT) => {
      const found = view().fleet.aircraft.find((candidate) => candidate.id === id);
      if (!found) throw new Error(`no aircraft ${id}`);
      return found;
    };
    const mission = (id = TRAINING): Mission => {
      const found = view().missions.missions.find((candidate) => candidate.id === id);
      if (!found) throw new Error(`no mission ${id}`);
      return found;
    };
    /** Runs until the mission is no longer active, in simulated minutes at 100x. */
    const runUntilFinished = (id: string) => {
      for (let i = 0; i < 2000 && mission(id).status === 'active'; i++) run(600);
    };
    return { database, runner, execute, run, view, aircraft, mission, runUntilFinished };
  }

  let session: Awaited<ReturnType<typeof openSession>>;
  let offerId = '';

  beforeAll(async () => {
    directory = mkdtempSync(join(tmpdir(), 'aegis-mission-scenario-'));
    path = join(directory, 'aegis.db');
    const setup = openNodeDatabase(path);
    let now = 1_800_000_000_000;
    await importReferenceData(setup.db, FLIGHT_REFERENCE_INPUTS, { now: () => (now += 1000) });
    setup.close();
    session = await openSession();
  });
  afterAll(() => {
    session.database.close();
    rmSync(directory, { recursive: true, force: true });
  });

  it('1-2. opens and shows the available aircraft', async () => {
    const { types, attributes } = await loadAircraftTypes();
    const homes = (
      await Promise.all(['EGPK', 'EGHQ'].map((icao) => loadAerodrome({ icao })))
    ).filter((row): row is NonNullable<typeof row> => row !== null) as AerodromeRow[];
    const { orders, missing } = starterOrders(buildCatalogue(types, attributes), homes);
    expect(missing).toEqual([]);

    session.execute({ type: 'setSpeed', speed: 100 });
    session.execute({ type: 'seedStarterFleet', aircraft: orders });

    expect(session.view().fleet.aircraft.map((a) => [a.id, a.typeName, a.status])).toEqual([
      ['AEGIS-FT-001', 'Eurofighter Typhoon', 'available'],
      ['AEGIS-FT-002', 'Eurofighter Typhoon', 'available'],
      ['AEGIS-TR-001', 'Airbus A400M Atlas', 'available'],
      ['AEGIS-TR-002', 'Boeing C-17 Globemaster III', 'available'],
    ]);
    expect(session.view().missions.missions).toEqual([]);
  });

  it('3-5. creates a Training mission, selects an aircraft and generates a route', () => {
    const aircraft = session.aircraft();
    if (!aircraft.location || !aircraft.performance) throw new Error('setup');
    const form = {
      ...blankForm('training'),
      title: 'Atlas navigation exercise',
      aircraftId: aircraft.id,
      target: suggestedTarget('training', aircraft.location, aircraft.performance.referenceRangeKm),
    };
    const configuration = configurationFromForm(form, aircraft, session.view().clock.tick, null);
    session.execute({ type: 'createMission', missionType: 'training', ...configuration });

    const mission = session.mission();
    expect(mission).toMatchObject({
      id: TRAINING,
      type: 'training',
      source: 'manual',
      status: 'planned',
      title: 'Atlas navigation exercise',
      aircraftId: AIRCRAFT,
    });
    expect(mission.plan?.points.map((point) => point.code ?? point.name)).toEqual([
      'EGHQ',
      'Training point',
      'EGHQ',
    ]);
    expect(mission.plan?.points[0]).toMatchObject({ kind: 'aerodrome', refId: 'ourairports:2448' });
  });

  it('6. edits the route with the flight planner’s own functions and saves it to the mission', () => {
    const mission = session.mission();
    const aircraft = session.aircraft();
    if (!mission.plan || !mission.load || !aircraft.performance) throw new Error('setup');
    const before = evaluationOf(mission, aircraft, session.view().clock.tick).plan?.estimate;

    // What the planner does: the mission's route becomes the one draft both the panel and the
    // map edit. Add a waypoint on the way home and drag it out over the Celtic Sea.
    const draft: PlanDraft = { aircraftId: aircraft.id, plan: mission.plan, load: mission.load };
    const edited = refuelForRoute(
      moveWaypoint(insertWaypoint(draft, 1), 2, 50.9, -8.5),
      aircraft.performance,
    );
    session.execute({
      type: 'updateMission',
      missionId: mission.id,
      ...configurationOf(mission),
      plan: edited.plan,
      load: edited.load,
    });

    const saved = session.mission();
    expect(saved.status).toBe('planned');
    expect(saved.plan?.points.map((point) => point.name)).toEqual([
      'Cornwall Airport Newquay',
      'Training point',
      'WP1',
      'Cornwall Airport Newquay',
    ]);
    expect(saved.plan?.points[2]).toMatchObject({ lat: 50.9, lon: -8.5 });
    const after = evaluationOf(saved, aircraft, session.view().clock.tick).plan?.estimate;
    expect(after?.distanceM).toBeGreaterThan(before?.distanceM ?? 0);
    expect(saved.load?.fuelKg).toBeGreaterThan(mission.load.fuelKg);
    // The objectives are the mission's own; editing the route did not change them.
    expect(saved.objectives).toEqual(mission.objectives);
  });

  it('7-8. reviews objectives, fuel, time and risk before committing', () => {
    const evaluation = evaluationOf(
      session.mission(),
      session.aircraft(),
      session.view().clock.tick,
    );
    expect(evaluation.acceptable).toBe(true);
    expect(evaluation.constraints.filter((c) => c.severity === 'block')).toEqual([]);

    // Objectives: the forecast says every one will be met as planned.
    expect(evaluation.forecast?.objectives.map((o) => [o.label, o.status])).toEqual([
      ['Pass within 10 km of Training point', 'complete'],
      ['Return to base', 'complete'],
      ['Land with reserve fuel', 'complete'],
      ['Finish with condition at or above 60 %', 'complete'],
    ]);

    // Fuel and time, from the flight planner.
    const estimate = evaluation.plan?.estimate;
    expect(estimate?.completes).toBe(true);
    expect(estimate?.durationS).toBeGreaterThan(20 * 60);
    expect(estimate?.fuelAtDestinationKg).toBeGreaterThanOrEqual(
      session.aircraft().performance?.reserveFuelKg ?? Infinity,
    );

    // Risk: a number, and the reasons for it.
    const risk = evaluation.risk;
    expect(risk?.index).toBeGreaterThanOrEqual(0);
    expect(risk?.index).toBeLessThan(30);
    expect(risk?.contributors).toHaveLength(7);
    expect(risk?.contributors.every((c) => c.explanation.length > 0)).toBe(true);
    expect(risk?.contributors.find((c) => c.id === 'aircraft_suitability')?.value).toBe(0);
  });

  it('9-10. accepts the mission and launches it when ready', () => {
    expect(readiness(session.mission(), session.aircraft()).ready).toBe(false);
    session.execute({ type: 'acceptMission', missionId: TRAINING });
    const accepted = session.mission();
    expect(accepted.status).toBe('accepted');
    expect(accepted.assessment?.risk.index).toBeDefined();
    expect(readiness(accepted, session.aircraft())).toEqual({ ready: true, issues: [] });

    // Committed: the aircraft cannot be sent anywhere else.
    expect(() => {
      session.execute({
        type: 'launchFlight',
        aircraftId: AIRCRAFT,
        plan: accepted.plan as NonNullable<Mission['plan']>,
        load: accepted.load as NonNullable<Mission['load']>,
      });
    }).toThrow(/committed to MSN-000001/);

    session.execute({ type: 'launchMission', missionId: TRAINING });
    expect(session.mission()).toMatchObject({ status: 'active', flightId: 'FLT-000001' });
    expect(session.aircraft()).toMatchObject({ status: 'in_flight', location: null });
  });

  it('11-12. the aircraft flies the mission and its objectives update along the way', () => {
    session.run(3000);
    const early = session.view().fleet.activeFlights[0];
    const earlyMission = session.mission();
    if (!early) throw new Error('flight should be active');
    expect(early.aircraftId).toBe(AIRCRAFT);
    expect(earlyMission.objectives[0]?.status).toBe('pending');
    const earlyProgress = missionProgress(earlyMission);
    expect(earlyProgress).toBeGreaterThan(0);

    // Fly on until the turning point has been passed.
    for (let i = 0; i < 400 && session.mission().objectives[0]?.status === 'pending'; i++) {
      session.run(500);
    }
    const later = session.view().fleet.activeFlights[0];
    const laterMission = session.mission();
    if (!later) throw new Error('flight should still be active');
    expect(laterMission.status).toBe('active');
    expect(laterMission.objectives[0]).toMatchObject({ status: 'complete', progress: 1 });
    expect(laterMission.objectives[1]?.status).toBe('pending');
    expect(missionProgress(laterMission)).toBeGreaterThan(earlyProgress);
    expect(later.distanceM).toBeGreaterThan(early.distanceM);
    expect(later.fuelKg).toBeLessThan(early.fuelKg);
    // The mission's route is on the map, flagged as flying.
    expect(missionFeatures([laterMission], TRAINING).routes.features[0]?.properties).toMatchObject({
      active: true,
      selected: true,
    });
  });

  it('13-14. the mission completes and the aircraft’s state is updated', () => {
    const launched = session.mission();
    session.runUntilFinished(TRAINING);

    const mission = session.mission();
    expect(mission.status).toBe('completed');
    expect(mission.objectives.every((objective) => objective.status === 'complete')).toBe(true);
    expect(mission.outcome).toMatchObject({
      result: 'completed',
      summary: 'All 2 required objectives met.',
      objectivesComplete: 2,
      objectivesRequired: 2,
    });
    // The outcome is what the planner said it would be when the mission was accepted.
    expect(mission.outcome?.flightDurationS).toBe(launched.assessment?.durationS);
    expect(mission.outcome?.fuelUsedKg).toBeCloseTo(launched.assessment?.fuelUsedKg ?? 0, 6);

    const aircraft = session.aircraft();
    expect(aircraft).toMatchObject({ status: 'available', flights: 1, activeFlightId: null });
    expect(aircraft.location?.code).toBe('EGHQ');
    expect(aircraft.conditionPct).toBeLessThan(100);
    expect(aircraft.fuelKg).toBeCloseTo(launched.assessment?.fuelAtDestinationKg ?? 0, 6);
    expect(aircraft.flightSecondsTotal).toBe(mission.outcome?.flightDurationS);
    expect(groupOf(mission.status)).toBe('history');
  });

  it('15-16. the mission’s history is on disk and the log holds the meaningful actions', async () => {
    await session.runner.flush();
    const row = session.database.transport.connection
      .prepare('SELECT status, aircraft_id, flight_id FROM sim_mission WHERE id = ?')
      .get(TRAINING);
    expect(row).toEqual({ status: 'completed', aircraft_id: AIRCRAFT, flight_id: 'FLT-000001' });

    const history = await loadMissionLog(TRAINING);
    expect(history.map((entry) => [entry.kind, entry.type, entry.actor])).toEqual([
      ['command', 'createMission', 'player'],
      ['command', 'updateMission', 'player'],
      ['command', 'acceptMission', 'player'],
      ['command', 'launchMission', 'player'],
      ['event', 'objectiveCompleted', 'world'],
      ['event', 'flightCompleted', 'world'],
      ['event', 'objectiveCompleted', 'world'],
      ['event', 'objectiveCompleted', 'world'],
      ['event', 'objectiveCompleted', 'world'],
      ['event', 'missionCompleted', 'world'],
    ]);
    // The edit is recorded with the whole route, waypoint included.
    const edit = history[1]?.payload as { plan: { points: { name: string }[] } };
    expect(edit.plan.points.map((point) => point.name)).toContain('WP1');
    // Ticks never go backwards, and sequence numbers never repeat.
    const ticks = history.map((entry) => entry.tick);
    expect(ticks).toEqual([...ticks].sort((a, b) => a - b));
    expect(new Set(history.map((entry) => entry.seq)).size).toBe(history.length);

    const recent = await loadRecentLog(100);
    expect(recent[0]?.seq).toBe(session.view().logLength);
    expect(recent.at(-1)).toMatchObject({ seq: 1, type: 'seedStarterFleet', actor: 'system' });
    // Pacing is not history.
    expect(recent.some((entry) => entry.type === 'setSpeed')).toBe(false);
  });

  it('17. closes and reopens to the same world', async () => {
    const atClose = session.view();
    session.database.close();

    session = await openSession();
    const reopened = session.view();
    expect(reopened.clock).toEqual(atClose.clock);
    expect(reopened.missions).toEqual(atClose.missions);
    expect(reopened.fleet).toEqual(atClose.fleet);
    expect(reopened.logLength).toBe(atClose.logLength);
    expect(reopened.integrityDigest).toBe(atClose.integrityDigest);
    expect(session.mission().outcome?.result).toBe('completed');
    expect(await loadMissionLog(TRAINING)).toHaveLength(10);
  });

  it('18. the world generates a separate opportunity', async () => {
    // What the application does once it has a fleet: copy the operating area into the world.
    const homes = session.view().fleet.aircraft.map((aircraft) => aircraft.home);
    const area = chooseOperatingArea(await loadLargeAerodromes(), homes);
    expect(area.map((place) => place.code)).toEqual([
      'EGPK',
      'EIDW',
      'EGCC',
      'EGLL',
      'LFPG',
      'EHAM',
      'KJFK',
    ]);
    session.execute({ type: 'setOperatingArea', places: area });
    expect(session.view().missions.operatingAreaSize).toBe(7);

    const hourMs = (GENERATION.intervalTicks * 1000) / 100;
    for (let hour = 0; hour < 200 && offerId === ''; hour++) {
      session.run(hourMs);
      offerId =
        session.view().missions.missions.find((mission) => mission.status === 'offered')?.id ?? '';
    }
    expect(offerId).toBe('MSN-000002');
    const offer = session.mission(offerId);
    expect(offer).toMatchObject({ source: 'generated', status: 'offered', aircraftId: null });
    expect(offer.description).toMatch(/^Simulated requirement\./);
    expect(offer.createdTick % GENERATION.intervalTicks).toBe(0);
    expect(offer.expiresTick).toBeGreaterThan(session.view().clock.tick);
  });

  it('19. the opportunity appears in the Missions interface, apart from the player’s own', () => {
    const missions = session.view().missions.missions;
    const filter = { type: 'all', sort: 'newest' } as const;
    expect(listMissions(missions, { ...filter, group: 'offers' }).map((m) => m.id)).toEqual([
      offerId,
    ]);
    expect(listMissions(missions, { ...filter, group: 'history' }).map((m) => m.id)).toEqual([
      TRAINING,
    ]);
    expect(listMissions(missions, { ...filter, group: 'all' }).map((m) => m.id)).toEqual([
      offerId,
      TRAINING,
    ]);
    // It is on the map before it has a route: where it asks to go.
    const features = missionFeatures(missions, offerId);
    expect(features.points.features.length + features.areas.features.length).toBeGreaterThan(0);
    expect(features.routes.features).toEqual([]);
  });

  it('20. takes the opportunity up and runs it through the same framework', async () => {
    const offer = session.mission(offerId);
    session.execute({ type: 'acceptOffer', missionId: offerId });
    expect(session.mission(offerId).status).toBe('draft');

    // Assign the first aircraft that suits the template and can fly it from where it is.
    const template = MISSION_TEMPLATES[offer.type];
    const tick = session.view().clock.tick;
    const candidate = session
      .view()
      .fleet.aircraft.filter(
        (aircraft) =>
          aircraft.status === 'available' &&
          template.suitableCategories.includes(aircraft.category),
      )
      .map((aircraft) => ({
        aircraft,
        configuration: configurationFromForm(
          { ...formFromMission(session.mission(offerId)), aircraftId: aircraft.id },
          aircraft,
          tick,
          session.mission(offerId),
        ),
      }))
      .find(({ aircraft, configuration }) => {
        const evaluation = evaluationOf(
          { ...session.mission(offerId), ...configuration, objectives: offer.objectives },
          aircraft,
          tick,
        );
        return evaluation.acceptable && objectivesMet(evaluation.forecast?.objectives ?? []);
      });
    if (!candidate) throw new Error('no aircraft in the fleet can fly the generated opportunity');

    session.execute({ type: 'updateMission', missionId: offerId, ...candidate.configuration });
    const planned = session.mission(offerId);
    expect(planned).toMatchObject({
      status: 'planned',
      source: 'generated',
      title: offer.title,
      completeByTick: offer.completeByTick,
      aircraftId: candidate.aircraft.id,
    });

    session.execute({ type: 'acceptMission', missionId: offerId });
    session.execute({ type: 'launchMission', missionId: offerId });
    expect(session.mission(offerId).status).toBe('active');
    session.runUntilFinished(offerId);

    const finished = session.mission(offerId);
    expect(finished).toMatchObject({ status: 'completed', outcome: { result: 'completed' } });
    const landedAt = session.aircraft(candidate.aircraft.id).location;
    const expected = offer.brief.destination ?? candidate.aircraft.location;
    expect(greatCircleDistance(landedAt as NonNullable<typeof landedAt>, expected)).toBeLessThan(
      1000,
    );

    // Its history reads like any other mission's, with the world's part at the start.
    await session.runner.flush();
    const history = (await loadMissionLog(offerId)).map((entry) => entry.type);
    expect(history.slice(0, 5)).toEqual([
      'opportunityGenerated',
      'acceptOffer',
      'updateMission',
      'acceptMission',
      'launchMission',
    ]);
    expect(history.at(-1)).toBe('missionCompleted');

    // And the whole world, both missions and the close and reopen included, is exactly what its
    // seed and its log produce.
    const saved = (await new SqliteWorldStore(session.database.db).load()) as Checkpoint;
    const log: LogEntry[] = (await loadRecentLog(100_000)).reverse();
    expect(log.map((entry) => entry.seq)).toEqual(log.map((_, index) => index + 1));
    const replayed = replayWorld(newWorld(), log, saved.snapshot.clock.tick);
    expect(replayComparable(replayed.snapshot())).toEqual(replayComparable(saved.snapshot));
  }, 60_000);
});
