//! Schema migrations (ADR 0003).
//!
//! The SQL is generated by drizzle-kit into `packages/db/migrations` and embedded here at compile
//! time. The Node runner in `packages/db/src/node/migrate.ts` follows the same rules and uses the
//! same tracking table; keep the two in step.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use include_dir::{include_dir, Dir};
use rusqlite::{Connection, TransactionBehavior};
use serde::Deserialize;
use sha2::{Digest, Sha256};

use crate::error::{AppError, AppResult};

static EMBEDDED: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/../../../packages/db/migrations");

const STATEMENT_BREAKPOINT: &str = "--> statement-breakpoint";

const TRACKING_TABLE: &str = "CREATE TABLE IF NOT EXISTS __aegis_migrations (
    idx INTEGER PRIMARY KEY,
    tag TEXT NOT NULL,
    checksum TEXT NOT NULL,
    applied_wall_ms INTEGER NOT NULL
)";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Migration {
    pub idx: i64,
    pub tag: String,
    pub sql: String,
}

impl Migration {
    /// SHA-256 of the SQL with line endings normalised, so CRLF and LF checkouts agree.
    fn checksum(&self) -> String {
        let digest = Sha256::digest(self.sql.replace("\r\n", "\n").as_bytes());
        digest.iter().map(|byte| format!("{byte:02x}")).collect()
    }
}

#[derive(Debug, Default, PartialEq, Eq)]
pub struct MigrationReport {
    /// Tags applied by this run, in order.
    pub applied: Vec<String>,
    /// Total number of migrations now recorded in the database.
    pub total: usize,
    /// Backup written before applying, if the database already held data.
    pub backup: Option<PathBuf>,
}

#[derive(Deserialize)]
struct Journal {
    entries: Vec<JournalEntry>,
}

#[derive(Deserialize)]
struct JournalEntry {
    idx: i64,
    tag: String,
}

fn migration_error(message: impl Into<String>) -> AppError {
    AppError::Migration(message.into())
}

/// The migrations compiled into this binary, in journal order.
pub fn embedded() -> AppResult<Vec<Migration>> {
    let journal_file = EMBEDDED
        .get_file("meta/_journal.json")
        .ok_or_else(|| migration_error("embedded migration journal is missing"))?;
    let journal: Journal = serde_json::from_slice(journal_file.contents())
        .map_err(|error| migration_error(format!("embedded journal is invalid: {error}")))?;

    let mut migrations = Vec::with_capacity(journal.entries.len());
    for entry in journal.entries {
        let file_name = format!("{}.sql", entry.tag);
        let sql = EMBEDDED
            .get_file(&file_name)
            .and_then(|file| file.contents_utf8())
            .ok_or_else(|| migration_error(format!("embedded migration {file_name} is missing")))?;
        migrations.push(Migration {
            idx: entry.idx,
            tag: entry.tag,
            sql: sql.to_owned(),
        });
    }
    migrations.sort_by_key(|migration| migration.idx);
    Ok(migrations)
}

fn wall_ms() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |elapsed| {
            i64::try_from(elapsed.as_millis()).unwrap_or(i64::MAX)
        })
}

/// Brings the database up to `migrations`.
///
/// - Each pending migration runs in its own transaction.
/// - An applied migration whose SQL has since changed is an error.
/// - A database holding a migration that is not in `migrations` is an error: it was written by a
///   newer build.
/// - If `backup_dir` is given and the database already has applied migrations, a consistent copy
///   is written there before anything pending is applied.
pub fn run(
    conn: &mut Connection,
    migrations: &[Migration],
    backup_dir: Option<&Path>,
) -> AppResult<MigrationReport> {
    conn.execute(TRACKING_TABLE, [])?;

    let applied: BTreeMap<i64, (String, String)> = {
        let mut statement = conn.prepare("SELECT idx, tag, checksum FROM __aegis_migrations")?;
        let rows = statement.query_map([], |row| Ok((row.get(0)?, (row.get(1)?, row.get(2)?))))?;
        rows.collect::<Result<_, _>>()?
    };

    let known: BTreeSet<i64> = migrations.iter().map(|migration| migration.idx).collect();
    if let Some((idx, (tag, _))) = applied.iter().find(|(idx, _)| !known.contains(idx)) {
        return Err(migration_error(format!(
            "database has migration {idx} ({tag}) that this build does not know; it was created by a newer version"
        )));
    }

    let mut pending = Vec::new();
    for migration in migrations {
        match applied.get(&migration.idx) {
            Some((tag, checksum)) => {
                if *tag != migration.tag || *checksum != migration.checksum() {
                    return Err(migration_error(format!(
                        "migration {} ({}) changed after it was applied",
                        migration.idx, migration.tag
                    )));
                }
            }
            None => pending.push(migration),
        }
    }

    let mut report = MigrationReport {
        total: applied.len(),
        ..MigrationReport::default()
    };

    if let (Some(dir), Some(first), false) = (backup_dir, pending.first(), applied.is_empty()) {
        std::fs::create_dir_all(dir)?;
        let path = dir.join(format!("aegis-before-{}-{}.db", first.tag, wall_ms()));
        let target = path
            .to_str()
            .ok_or_else(|| migration_error("backup path is not valid UTF-8"))?;
        conn.execute("VACUUM INTO ?1", [target])?;
        report.backup = Some(path);
    }

    for migration in pending {
        let tx = conn.transaction_with_behavior(TransactionBehavior::Immediate)?;
        for statement in migration.sql.split(STATEMENT_BREAKPOINT) {
            if !statement.trim().is_empty() {
                tx.execute_batch(statement).map_err(|error| {
                    migration_error(format!(
                        "migration {} ({}) failed: {error}",
                        migration.idx, migration.tag
                    ))
                })?;
            }
        }
        tx.execute(
            "INSERT INTO __aegis_migrations (idx, tag, checksum, applied_wall_ms) VALUES (?1, ?2, ?3, ?4)",
            rusqlite::params![migration.idx, migration.tag, migration.checksum(), wall_ms()],
        )?;
        tx.commit()?;
        report.applied.push(migration.tag.clone());
        report.total += 1;
    }

    Ok(report)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn migration(idx: i64, tag: &str, sql: &str) -> Migration {
        Migration {
            idx,
            tag: tag.into(),
            sql: sql.into(),
        }
    }

    fn table_names(conn: &Connection) -> Vec<String> {
        let mut statement = conn
            .prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE '\\_\\_%' ESCAPE '\\' ORDER BY name")
            .unwrap();
        let names = statement
            .query_map([], |row| row.get(0))
            .unwrap()
            .collect::<Result<Vec<String>, _>>()
            .unwrap();
        names
    }

    #[test]
    fn embedded_migrations_apply_to_an_empty_database() {
        let mut conn = Connection::open_in_memory().unwrap();
        let migrations = embedded().unwrap();
        assert!(!migrations.is_empty());

        let report = run(&mut conn, &migrations, None).unwrap();
        assert_eq!(report.applied.len(), migrations.len());
        assert_eq!(report.applied[0], "0000_init");
        let tables = table_names(&conn);
        for expected in [
            "sim_world",
            "sim_clock",
            "ref_location",
            "ref_runway",
            "ref_pack_install",
        ] {
            assert!(
                tables.iter().any(|name| name == expected),
                "missing table {expected}"
            );
        }
    }

    #[test]
    fn running_twice_applies_nothing_the_second_time() {
        let mut conn = Connection::open_in_memory().unwrap();
        let migrations = embedded().unwrap();
        run(&mut conn, &migrations, None).unwrap();
        let second = run(&mut conn, &migrations, None).unwrap();
        assert!(second.applied.is_empty());
        assert_eq!(second.total, migrations.len());
    }

    #[test]
    fn a_failing_migration_is_rolled_back_completely() {
        let mut conn = Connection::open_in_memory().unwrap();
        let broken = [migration(
            0,
            "0000_broken",
            "CREATE TABLE a (x);--> statement-breakpoint\nCREATE TABLE a (x);",
        )];
        assert!(matches!(
            run(&mut conn, &broken, None),
            Err(AppError::Migration(_))
        ));
        assert!(table_names(&conn).is_empty());
    }

    #[test]
    fn an_edited_migration_is_detected() {
        let mut conn = Connection::open_in_memory().unwrap();
        run(
            &mut conn,
            &[migration(0, "0000_a", "CREATE TABLE a (x);")],
            None,
        )
        .unwrap();
        let edited = [migration(0, "0000_a", "CREATE TABLE a (x, y);")];
        let error = run(&mut conn, &edited, None).unwrap_err();
        assert!(error.to_string().contains("changed after it was applied"));
    }

    #[test]
    fn line_endings_do_not_affect_the_checksum() {
        let lf = migration(0, "0000_a", "CREATE TABLE a (\n  x\n);\n");
        let crlf = migration(0, "0000_a", "CREATE TABLE a (\r\n  x\r\n);\r\n");
        assert_eq!(lf.checksum(), crlf.checksum());
    }

    #[test]
    fn a_database_from_a_newer_build_is_refused() {
        let mut conn = Connection::open_in_memory().unwrap();
        let newer = [
            migration(0, "0000_a", "CREATE TABLE a (x);"),
            migration(1, "0001_b", "CREATE TABLE b (x);"),
        ];
        run(&mut conn, &newer, None).unwrap();
        let error = run(&mut conn, &newer[..1], None).unwrap_err();
        assert!(error.to_string().contains("newer version"));
    }

    #[test]
    fn an_existing_database_is_backed_up_before_new_migrations() {
        let dir = tempfile::tempdir().unwrap();
        let backups = dir.path().join("backups");
        let mut conn = Connection::open(dir.path().join("aegis.db")).unwrap();

        let first = [migration(0, "0000_a", "CREATE TABLE a (x);")];
        let report = run(&mut conn, &first, Some(&backups)).unwrap();
        assert_eq!(report.backup, None, "a new database needs no backup");
        conn.execute("INSERT INTO a (x) VALUES (41)", []).unwrap();

        let both = [
            first[0].clone(),
            migration(1, "0001_b", "UPDATE a SET x = x + 1;"),
        ];
        let report = run(&mut conn, &both, Some(&backups)).unwrap();
        let backup = report.backup.expect("backup should have been written");

        let before: i64 = Connection::open(backup)
            .unwrap()
            .query_row("SELECT x FROM a", [], |row| row.get(0))
            .unwrap();
        let after: i64 = conn
            .query_row("SELECT x FROM a", [], |row| row.get(0))
            .unwrap();
        assert_eq!((before, after), (41, 42));
    }
}
