import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { DatabaseSync } from 'node:sqlite';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';

/** The migrations generated by drizzle-kit and embedded into the desktop binary. */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL('../../migrations', import.meta.url));

const STATEMENT_BREAKPOINT = '--> statement-breakpoint';

const journalSchema = z.object({
  entries: z.array(z.object({ idx: z.int().nonnegative(), tag: z.string().min(1) })),
});

export class MigrationError extends Error {
  override readonly name = 'MigrationError';
}

/**
 * Brings a database up to the current schema.
 *
 * This is the Node counterpart of the migration runner in the Rust core
 * (`src-tauri/src/db/migrations.rs`). Both follow the same rules and use the same tracking table:
 * - migrations run in journal order, each in its own transaction;
 * - an applied migration whose file has since changed is an error;
 * - a database with migrations this build does not know is an error.
 *
 * @returns the tags of the migrations applied by this call.
 */
export function migrate(connection: DatabaseSync, folder = MIGRATIONS_FOLDER): string[] {
  const journal = journalSchema.parse(
    JSON.parse(readFileSync(join(folder, 'meta', '_journal.json'), 'utf8')),
  );
  const entries = [...journal.entries].sort((a, b) => a.idx - b.idx);

  connection.exec(`
    CREATE TABLE IF NOT EXISTS __aegis_migrations (
      idx INTEGER PRIMARY KEY,
      tag TEXT NOT NULL,
      checksum TEXT NOT NULL,
      applied_wall_ms INTEGER NOT NULL
    )`);

  const applied = new Map<number, { tag: string; checksum: string }>();
  for (const row of connection.prepare('SELECT idx, tag, checksum FROM __aegis_migrations').all()) {
    applied.set(Number(row.idx), { tag: String(row.tag), checksum: String(row.checksum) });
  }

  const known = new Set(entries.map((entry) => entry.idx));
  for (const [idx, { tag }] of applied) {
    if (!known.has(idx)) {
      throw new MigrationError(
        `Database has migration ${idx} (${tag}) that this build does not know; it was created by a newer version`,
      );
    }
  }

  const newlyApplied: string[] = [];
  for (const { idx, tag } of entries) {
    // Line endings are normalised so a checkout with CRLF files yields the same checksum.
    const text = readFileSync(join(folder, `${tag}.sql`), 'utf8').replaceAll('\r\n', '\n');
    const checksum = createHash('sha256').update(text).digest('hex');

    const previous = applied.get(idx);
    if (previous) {
      if (previous.tag !== tag || previous.checksum !== checksum) {
        throw new MigrationError(`Migration ${idx} (${tag}) changed after it was applied`);
      }
      continue;
    }

    connection.exec('BEGIN IMMEDIATE');
    try {
      for (const statement of text.split(STATEMENT_BREAKPOINT)) {
        if (statement.trim().length > 0) {
          connection.exec(statement);
        }
      }
      connection
        .prepare(
          'INSERT INTO __aegis_migrations (idx, tag, checksum, applied_wall_ms) VALUES (?, ?, ?, ?)',
        )
        .run(idx, tag, checksum, Date.now());
      connection.exec('COMMIT');
    } catch (cause) {
      connection.exec('ROLLBACK');
      throw new MigrationError(`Migration ${idx} (${tag}) failed`, { cause });
    }
    newlyApplied.push(tag);
  }
  return newlyApplied;
}
