import { MISSION_TEMPLATES, isFinished, type Mission } from '@aegis/domain';
import type { AircraftState, LogEntry } from '@aegis/sim';
import {
  Button,
  ConstraintList,
  DataField,
  DataList,
  DataTable,
  Hint,
  Meter,
  Notice,
  PageHeader,
  Panel,
} from '@aegis/ui';
import { Check, MapPin, Pencil, Route, Send, Undo2, X } from 'lucide-react';
import { useMemo } from 'react';
import { useNavigate } from 'react-router';
import { formatDuration, formatInteger, formatKg, formatKm } from '../../format';
import { focusMission } from '../../map/mission-binding';
import {
  evaluationOf,
  missionPlace,
  missionProgress,
  readiness,
  routeSummary,
} from '../../missions/mission-logic';
import {
  acceptMission,
  acceptOffer,
  cancelMission,
  launchMission,
  rejectOffer,
  releaseMission,
} from '../../missions/service';
import { loadMissionLog } from '../../sim/log-queries';
import { beginMissionPlanning } from '../../state/plan-store';
import { useSimStore } from '../../state/sim-store';
import {
  MissionStatusBadge,
  ObjectiveList,
  PriorityBadge,
  RiskBreakdown,
  SourceBadge,
  formatTick,
  relativeTick,
  typeLabel,
} from '../shared/mission-display';
import { useAsync } from '../shared/useAsync';
import { useLastReady, useStable } from '../shared/useStable';

/** Words for log entries, so that history reads as events and not as command names. */
const LOG_WORDS: Readonly<Record<string, string>> = {
  createMission: 'Mission created',
  updateMission: 'Mission edited',
  acceptOffer: 'Opportunity taken up',
  rejectOffer: 'Opportunity rejected',
  acceptMission: 'Mission accepted; aircraft assigned',
  releaseMission: 'Acceptance withdrawn; aircraft released',
  cancelMission: 'Mission cancelled',
  launchMission: 'Mission launched',
  opportunityGenerated: 'Opportunity generated',
  opportunityExpired: 'Opportunity expired',
  objectiveCompleted: 'Objective completed',
  objectiveFailed: 'Objective failed',
  flightCompleted: 'Flight landed',
  flightFuelExhausted: 'Flight ran out of fuel',
  missionCompleted: 'Mission completed',
  missionFailed: 'Mission failed',
};

function logDetail(entry: LogEntry): string {
  const { payload } = entry;
  const text = (key: string) => (typeof payload[key] === 'string' ? payload[key] : null);
  return text('label') ?? text('summary') ?? text('title') ?? entry.flightId ?? '';
}

function HistoryPanel({ mission }: { readonly mission: Mission }) {
  const epoch = useSimStore((state) => state.view?.epoch ?? null);
  // The log is read from the database, which follows the simulation by one checkpoint.
  const persisted = useSimStore((state) => state.view?.checkpoint.persistedSeq ?? 0);
  const log = useAsync(`mission-log:${mission.id}:${persisted}`, () => loadMissionLog(mission.id));
  const entries = useLastReady(log);

  return (
    <Panel title="History">
      {log.status === 'failed' && <Hint>The history could not be read: {log.error}</Hint>}
      {entries?.length === 0 && <Hint>Nothing recorded yet.</Hint>}
      {entries && entries.length > 0 && (
        <DataTable<LogEntry>
          caption={`History of ${mission.id}`}
          rows={entries}
          rowKey={(entry) => String(entry.seq)}
          columns={[
            {
              header: 'Sim time (UTC)',
              numeric: true,
              cell: (entry) => formatTick(epoch, entry.tick),
            },
            { header: 'Event', cell: (entry) => LOG_WORDS[entry.type] ?? entry.type },
            { header: 'Detail', cell: logDetail },
            { header: 'By', cell: (entry) => entry.actor },
          ]}
        />
      )}
      {!entries && log.status === 'loading' && <Hint>Reading the history.</Hint>}
    </Panel>
  );
}

function OverviewPanel({
  mission,
  aircraft,
}: {
  readonly mission: Mission;
  readonly aircraft: AircraftState | undefined;
}) {
  const epoch = useSimStore((state) => state.view?.epoch ?? null);
  const tick = useSimStore((state) => state.view?.clock.tick ?? 0);
  const when = (value: number | null) => {
    const at = formatTick(epoch, value);
    return at === null ? null : `${at} (${relativeTick(tick, value) ?? ''})`;
  };
  return (
    <Panel title="Overview">
      <DataList>
        <DataField label="Type" value={typeLabel(mission)} prose />
        <DataField
          label="Origin"
          value={mission.source === 'generated' ? 'Generated by the world' : 'Created manually'}
          prose
        />
        <DataField
          label="Aircraft"
          value={aircraft ? `${aircraft.id} · ${aircraft.typeName}` : mission.aircraftId}
          prose
        />
        <DataField label="Route" value={routeSummary(mission)} prose />
        <DataField label="Created" value={formatTick(epoch, mission.createdTick)} />
        <DataField label="Accepted" value={formatTick(epoch, mission.acceptedTick)} />
        {mission.status === 'offered' && (
          <DataField label="Answer by" value={when(mission.expiresTick)} />
        )}
        <DataField label="Planned start" value={when(mission.plannedStartTick)} />
        <DataField label="Complete by" value={when(mission.completeByTick)} />
        <DataField label="Launched" value={formatTick(epoch, mission.actualStartTick)} />
        <DataField label="Finished" value={formatTick(epoch, mission.completedTick)} />
        <DataField
          label="Payload to deliver"
          value={mission.brief.payloadKg > 0 ? formatKg(mission.brief.payloadKg) : null}
        />
      </DataList>
      {mission.outcome && (
        <div className="mt-3">
          <Notice
            tone={mission.outcome.result === 'completed' ? 'info' : 'warn'}
            title={mission.outcome.result === 'completed' ? 'Mission completed' : 'Mission failed'}
          >
            {mission.outcome.summary}
          </Notice>
        </div>
      )}
    </Panel>
  );
}

function PlanPanel({
  mission,
  evaluation,
}: {
  readonly mission: Mission;
  readonly evaluation: ReturnType<typeof evaluationOf> | null;
}) {
  const estimate = evaluation?.plan?.estimate ?? null;
  const recorded = mission.assessment;
  const outcome = mission.outcome;
  // Before launch the figures are live; afterwards they are what was recorded at acceptance.
  const figures = estimate
    ? {
        distanceM: estimate.distanceM,
        durationS: estimate.durationS,
        fuelUsedKg: estimate.fuelUsedKg,
        fuelAtDestinationKg: estimate.fuelAtDestinationKg,
      }
    : recorded;
  return (
    <Panel title="Route and fuel">
      {figures ? (
        <DataList>
          <DataField label="Distance" value={formatKm(figures.distanceM)} />
          <DataField label="Estimated flight time" value={formatDuration(figures.durationS)} />
          <DataField
            label="Estimated fuel used"
            value={formatKg(figures.fuelUsedKg)}
            hint="Simulated quantity, from the flight model."
          />
          <DataField
            label="Estimated fuel on landing"
            value={formatKg(figures.fuelAtDestinationKg)}
          />
          <DataField
            label="Fuel loaded"
            value={mission.load ? formatKg(mission.load.fuelKg) : null}
          />
          <DataField
            label="Payload loaded"
            value={mission.load ? formatKg(mission.load.payloadKg) : null}
          />
          <DataField
            label="Waypoints"
            value={mission.plan ? formatInteger(Math.max(mission.plan.points.length - 2, 0)) : null}
          />
          <DataField
            label="Cruise"
            value={
              mission.plan
                ? `${formatInteger(mission.plan.cruiseAltitudeM)} m · ${formatInteger(mission.plan.cruiseSpeedKmh)} km/h`
                : null
            }
          />
          {outcome?.flightDurationS != null && (
            <DataField label="Actual flight time" value={formatDuration(outcome.flightDurationS)} />
          )}
          {outcome?.fuelUsedKg != null && (
            <DataField label="Actual fuel used" value={formatKg(outcome.fuelUsedKg)} />
          )}
        </DataList>
      ) : (
        <Hint>
          No route yet. Assign an aircraft and say where the mission goes; the template then routes
          it, and the route can be edited on the map.
        </Hint>
      )}
    </Panel>
  );
}

export interface MissionDetailProps {
  readonly mission: Mission;
  readonly onEdit: () => void;
}

/** Everything about one mission, and the actions its state allows. */
export function MissionDetail({ mission, onEdit }: MissionDetailProps) {
  const navigate = useNavigate();
  const aircraft = useSimStore((state) =>
    state.view?.fleet.aircraft.find((candidate) => candidate.id === mission.aircraftId),
  );
  // Evaluate against ten-minute marks, not every tick: deadlines move slowly against the forecast.
  const hourTick = useSimStore((state) => {
    const tick = state.view?.clock.tick ?? 0;
    return tick - (tick % 600);
  });
  const open = !isFinished(mission.status) && mission.status !== 'active';
  // The forecast flies the whole route, so it is recomputed only when its inputs really change.
  const stableMission = useStable(mission);
  const stableAircraft = useStable(aircraft);
  const evaluation = useMemo(
    () => (open ? evaluationOf(stableMission, stableAircraft, hourTick) : null),
    [open, stableMission, stableAircraft, hourTick],
  );
  const ready = readiness(mission, aircraft);
  const risk = evaluation?.risk ?? mission.assessment?.risk ?? null;
  // Before launch, show what the plan will do to each objective; afterwards, what happened.
  const forecast = open && mission.status !== 'offered' ? (evaluation?.forecast ?? null) : null;
  const forecasting = forecast !== null;
  const objectives = forecast ? forecast.objectives : mission.objectives;
  const template = MISSION_TEMPLATES[mission.type];

  const showOnMap = () => {
    focusMission(mission);
    void navigate('/operations');
  };
  const editRoute = () => {
    if (!mission.plan || !mission.load || !mission.aircraftId) return;
    beginMissionPlanning(mission.id, {
      aircraftId: mission.aircraftId,
      plan: mission.plan,
      load: mission.load,
    });
    focusMission(mission);
    void navigate('/operations');
  };

  return (
    <div className="flex max-w-5xl flex-col gap-4">
      <PageHeader
        kicker={`${template.label} mission`}
        title={mission.id}
        subtitle={mission.title}
        badges={
          <>
            <SourceBadge mission={mission} />
            <MissionStatusBadge status={mission.status} />
            <PriorityBadge priority={mission.priority} />
          </>
        }
        actions={
          <>
            {(mission.plan ?? missionPlace(mission.brief)) && (
              <Button icon={MapPin} onClick={showOnMap}>
                Show on map
              </Button>
            )}
            {mission.status === 'offered' && (
              <>
                <Button
                  icon={X}
                  onClick={() => {
                    rejectOffer(mission.id);
                  }}
                >
                  Reject
                </Button>
                <Button
                  variant="primary"
                  icon={Check}
                  onClick={() => {
                    acceptOffer(mission.id);
                    onEdit();
                  }}
                >
                  Take up
                </Button>
              </>
            )}
            {(mission.status === 'draft' || mission.status === 'planned') && (
              <>
                <Button
                  icon={X}
                  onClick={() => {
                    cancelMission(mission.id);
                  }}
                >
                  Cancel mission
                </Button>
                <Button icon={Pencil} onClick={onEdit}>
                  Edit
                </Button>
              </>
            )}
            {mission.status === 'planned' && (
              <>
                <Button icon={Route} onClick={editRoute}>
                  Edit route
                </Button>
                <Button
                  variant="primary"
                  icon={Check}
                  disabled={!evaluation?.acceptable}
                  title={
                    evaluation?.acceptable ? undefined : 'Resolve the blocking constraints first.'
                  }
                  onClick={() => {
                    acceptMission(mission.id);
                  }}
                >
                  Accept
                </Button>
              </>
            )}
            {mission.status === 'accepted' && (
              <>
                <Button
                  icon={X}
                  onClick={() => {
                    cancelMission(mission.id);
                  }}
                >
                  Cancel mission
                </Button>
                <Button
                  icon={Undo2}
                  onClick={() => {
                    releaseMission(mission.id);
                  }}
                >
                  Release
                </Button>
                <Button
                  variant="primary"
                  icon={Send}
                  disabled={!ready.ready}
                  title={ready.ready ? undefined : ready.issues.join(' ')}
                  onClick={() => {
                    launchMission(mission.id);
                  }}
                >
                  Launch
                </Button>
              </>
            )}
          </>
        }
      />
      <p className="cursor-text text-sm text-ink-secondary select-text">{mission.description}</p>

      {mission.status === 'accepted' && (
        <Notice
          tone={ready.ready ? 'info' : 'warn'}
          title={ready.ready ? 'Ready to launch' : 'Not ready to launch'}
        >
          {ready.ready
            ? 'The aircraft is available at the origin. Launch when you are ready.'
            : ready.issues.join(' ')}
        </Notice>
      )}
      {mission.status === 'active' && (
        <Panel title="Progress">
          <Meter
            label="Required objectives"
            value={missionProgress(mission)}
            reading={`${mission.objectives.filter((o) => o.required && o.status === 'complete').length} of ${mission.objectives.filter((o) => o.required).length} complete`}
            tone="ok"
          />
        </Panel>
      )}

      <div className="grid grid-cols-2 gap-4">
        <OverviewPanel mission={mission} aircraft={aircraft} />
        <Panel title={forecasting ? 'Objectives (forecast)' : 'Objectives'}>
          <div className="flex flex-col gap-3">
            <ObjectiveList objectives={objectives} forecast={forecasting} />
            {forecasting && (
              <Hint>
                Forecast: what each objective will do if the mission is flown as planned, launched
                now. It is recalculated when the plan changes.
              </Hint>
            )}
          </div>
        </Panel>
        <PlanPanel mission={mission} evaluation={evaluation} />
        <Panel title="Risk">
          {risk ? (
            <RiskBreakdown risk={risk} />
          ) : (
            <Hint>Risk is assessed once the mission has an aircraft and a route.</Hint>
          )}
        </Panel>
      </div>

      {evaluation && evaluation.constraints.length > 0 && mission.status !== 'offered' && (
        <Panel title="Constraints">
          <ConstraintList items={evaluation.constraints} />
        </Panel>
      )}
      <HistoryPanel mission={mission} />
    </div>
  );
}
